BioTrananWebApp/Models/ErrorViewModel.cs
namespace BioTrananWebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

BioTrananWebApp/Controllers/BookingController.cs
using System.Net.Http.Headers;
using BioTrananDomain.DtoModels;
using BioTrananDomain.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace BioTrananWebApp.Controllers;

public class BookingController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;

    public BookingController(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }
    
    // GET: Booking/{id}
    [HttpGet("{id}")]
    public async Task<IActionResult> GetBooking(string id)
    {
        var httpClient = _httpClientFactory.CreateClient("WebApi");
        Showing showing;

        try
        {
            showing = await httpClient.GetFromJsonAsync<Showing>($"api/Showing/{id}");
        }
        catch (Exception e)
        {
            return View(null);
        }


        return View(showing);
    }

    // POST: Booking/{id}
    [HttpPost("{id}")]
    public async Task<IActionResult> PostBooking(string id)
    {
        var httpClient = _httpClientFactory.CreateClient("WebApi");

        if (string.IsNullOrWhiteSpace(Request.Form["Email"])) return View(null);
        if (!int.TryParse(Request.Form["Seats"], out int seats)) return View(null);

        HttpResponseMessage result;
        Reservation reservation;
        ReservationDto reservationDto = new ReservationDto
        {
            ReservationShowingId = id,
            Email = Request.Form["Email"]!,
            AmountOfSeats = seats,
        };

        var serializedData = JsonSerializer.Serialize(reservationDto);
        var buffer = System.Text.Encoding.UTF8.GetBytes(serializedData);
        var byteContent = new ByteArrayContent(buffer);
        byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

        try
        {
            result = await httpClient.PostAsync("/api/Reservation", byteContent);
            reservation = await result.Content.ReadFromJsonAsync<Reservation>();
        }
        catch (Exception e)
        {
            return View(null);
        }

        return View(reservation);
    }
}

BioTrananWebApp/Controllers/CancelController.cs
using Microsoft.AspNetCore.Mvc;

namespace BioTrananWebApp.Controllers;

public class CancelController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;

    public CancelController(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }
    
    // GET: Cancel/Reservation
    [HttpGet]
    public IActionResult Reservation()
    {
        return View();
    }

    // POST: Cancel/Reservation
    [HttpPost("Cancel/Reservation")]
    public async Task<IActionResult> CancelResult()
    {
        var httpClient = _httpClientFactory.CreateClient("WebApi");


        if (string.IsNullOrWhiteSpace(Request.Form["Id"])) return View(false);

        try
        {
            var response = await httpClient.DeleteAsync($"/api/reservation/{Request.Form["Id"]}");
            if (!response.IsSuccessStatusCode)
            {
                return View(false);
            }
        }
        catch (Exception e)
        {
            return View(false);
        }

        return View(true);
    }
}

BioTrananWebApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BioTrananDomain.Models;
using BioTrananWebApp.Models;

namespace BioTrananWebApp.Controllers;

public class HomeController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;

    public HomeController(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }

    // GET: Home/Index
    public async Task<IActionResult> Index()
    {
        HttpClient httpClient;
        List<Showing> showings;

        try
        {
            httpClient = _httpClientFactory.CreateClient("WebApi");
            showings = await httpClient.GetFromJsonAsync<List<Showing>>("api/Showing/GetUpcomingShowings");
        }
        catch (Exception e)
        {
            showings = new List<Showing>();
        }

        try
        {
            httpClient = _httpClientFactory.CreateClient("ChuckApi");
            ChuckJoke chuckJoke = await httpClient.GetFromJsonAsync<ChuckJoke>("jokes/random");
            ViewBag.Joke = chuckJoke.Value;
        }
        catch (Exception e)
        {
            ViewBag.Joke = "No Chuck Jokes today :(";
        }

        return View(showings);
    }

    // GET: Home/Privacy
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BioTrananWebApp/Controllers/MovieController.cs
using BioTrananDomain.Models;
using Microsoft.AspNetCore.Mvc;

namespace BioTrananWebApp.Controllers;

public class MovieController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;

    public MovieController(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }
    
    // GET: Movie/GetMovie/{movieId}
    [HttpGet("Movie/GetMovie/{movieId}")]
    public async Task<IActionResult> GetMovie(string movieId)
    {
        var httpClient = _httpClientFactory.CreateClient("WebApi");
        Movie movie;

        try
        {
            movie = await httpClient.GetFromJsonAsync<Movie>($"api/Movie/{movieId}");
        }
        catch (Exception e)
        {
            return View(null);
        }

        return View(movie);
    }
}

BioTrananWebApp/Views/Booking/GetBooking.cshtml
@model BioTrananDomain.Models.Showing

@{
    ViewBag.Title = "Create Booking";
    Layout = "_Layout";
}

<h2>Create reservation:</h2>

<body>
<div>
    <p>
        Creating booking for movie: @Model.ShowingMovie.MovieName
    </p>
</div>
<div>
    @using (Html.BeginForm())
    {
        <div>
            <input type="text" id="Id" value="@Model.Id" hidden="hidden"/>
            Email: <input type="email" id="Email" name="Email" value=""><br/>
            Seats: <input type="number" id="Seats" name="Seats" value=""><br/>
        </div>
        <div>
            <br/>
            <input type="button"
                   value="Go Back"
                   class="btn btn-primary"
                   onclick="location.href='@Url.Action("Index", "Home")'"/>
            
            <input type="submit"
                   class="btn btn-primary"/>
        </div>
    }
</div>
</body>

BioTrananWebApp/Views/Booking/PostBooking.cshtml
@model BioTrananDomain.Models.Reservation

@{
    ViewBag.Title = "Reservation Confirmation";
    Layout = "_Layout";
}

<body>
@if (Model != null)
{
    <div>
        <h2>Thank you for your reservation!</h2>
        <p>Reservation created for: @Model.ReservationShowing.ShowingMovie.MovieName</p>
        <p>Please remember your reservation Id: @Model.Id</p>
    </div>
}
else
{
    <div>
        <h2>Error, Please fill out the form!</h2>
    </div>
}
<div>
    <input type="button"
           value="Go Back to home"
           class="btn btn-primary"
           onclick="location.href='@Url.Action("Index", "Home")'"/>
</div>
</body>

BioTrananWebApp/Views/Cancel/CancelResult.cshtml
@model bool

@{
    ViewBag.Title = "Reservation cancel result";
    Layout = "_Layout";
}

<h2>Reservation cancel result:</h2>
@if (!Model)
{
    <p>
        No found match for your given Id, If you have forgotten your Id. You can't cancel!
    </p>
}
else
{
    <p>
        Successfully cancelled your reservation! Come again!
    </p>
}
<br/>
<input type="button"
       value="Go Back"
       class="btn btn-primary"
       onclick="location.href='@Url.Action("Index", "Home")'"/>

BioTrananWebApp/Views/Cancel/Reservation.cshtml
@{
    ViewBag.Title = "Cancel";
    Layout = "_Layout";
}

<h2>Booking Cancellation:</h2>
<p>Enter your Reservation Id: </p>
@using (Html.BeginForm())
{
    <div>
        Reservation Id: <input type="text" id="Id" name="Id" value=""><br/>
    </div>
    <div>
        <br/>
        <input type="button"
               value="Go Back"
               class="btn btn-primary"
               onclick="location.href='@Url.Action("Index", "Home")'"/>

        <input type="submit"
               class="btn btn-primary"/>
    </div>
}

BioTrananWebApp/Views/Home/Index.cshtml
@model List<BioTrananDomain.Models.Showing>

@{
    ViewData["Title"] = "Home Page";
}

<body>
<div class="text-center">
    <h1 class="display-4">Welcome to Bio Tranan</h1>
    <p>@ViewBag.Joke</p>
</div>

<h2>Showing Schedule</h2>
<div>
    @if (Model.Count == 0)
    {
        <p>Come back another time! No showings scheduled! :(</p>
    }
    else
    {
        <ul>
            @foreach (var showing in @Model)
            {
                <li>
                    <ul>
                        <li>
                            <b>Movie name:</b> @showing.ShowingMovie.MovieName
                            <input type="button"
                                   value="Movie Details"
                                   class="link link-dark"
                                   onclick="location.href= '@Url.Action("GetMovie", "Movie", new { id = showing.ShowingMovie.Id })'"/>
                        </li>
                        <li>
                            <b>Seats left:</b> @showing.SeatsLeft left out of @showing.ShowingSalon.SalonSeatAmount
                        </li>
                        <li>
                            <b>Salon:</b> @showing.ShowingSalon.SalonName
                        </li>
                        <li>
                            <b>Start time (GMT+2):</b> @showing.ShowingDateAndTime
                        </li>
                    </ul>
                    @if (showing.SeatsLeft < 1)
                    {
                        <input type="button"
                               class="btn btn-danger"
                               value="Sold out!"/>
                    }
                    else
                    {
                        <input type="button"
                               value="Create Reservation"
                               class="btn btn-primary"
                               onclick="location.href= '@Url.Action("GetBooking", "Booking", new { id = showing.Id })'"/>
                    }
                    <p></p>
                </li>
            }
        </ul>
    }

    <img src="/CATS-AND-POPCORN.jpg"/>
</div>
</body>

BioTrananWebApp/Views/Movie/GetMovie.cshtml
@model BioTrananDomain.Models.Movie

@{
    ViewBag.Title = "Movie Details";
    Layout = "_Layout";
}

<body>
<h2>Movie Details:</h2>
<div>
    @if (@Model == null)
    {
        <p>No result for search! :(</p>
    }
    else
    {
        <ul>
            <li>
                <b>Movie name:</b> @Model.MovieName
            </li>
            <li>
                <b>Movie Length: </b>@Model.MovieLengthInMinutes minutes<br/>
                <b>Movie Trailer:</b><br/>
                <iframe width="560"
                        height="315"
                        src="@Model.MovieEmbeddedTrailerUrl"
                        title="YouTube video player"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        allowfullscreen>
                </iframe>

            </li>
        </ul>
    }
</div>
<div>
    <input type="button"
           value="Go Back"
           class="btn btn-primary"
           onclick="location.href='@Url.Action("Index", "Home")'" />
</div>
</body>

BioTrananWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BioTrananWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/BioTrananWebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BioTrananWebApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cancel" asp-action="Reservation">Cancel Reservation</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - BioTrananWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>